### PR TITLE
Feature/update in place

### PR DESCRIPTION
**Pull request by bradder555**
### Behavior changed
The default behavior has been changed to update the resource.json file in-place provided that the referenced files have changed.

### New Flags
Consequentially, there are a couple extra flags
--no-replace / -nr, this will NOT replace the file in-place
--console / -c, this will print the updated resource.json file to the console,
--force, this is a hidden option mostly used to maintain compatibility with existing tests

### Modified Flags
--timestamp / -t has been modified to hidden, as IMHO, the timestamp should only change when the signature is created

### Sundries
Dependency versions were bumped and some explicit versions were added to mitigate a conflict

### CODE REVIEW

**Comment by paul-griffith** [comment]
Very cool! I had no idea anyone was actually using this; thanks a ton for contributing back.
I'll go through these changes soon. I'll probably also 'modernize' this repo a little to include automatic releases and maybe look into automatic graalvm AOT compiling to get 'native' executables for easier integration into workflows.

**Comment by paul-griffith** [comment]
I wonder if the CLI might end up cleaner if it was just subcommands, instead of changing the output format with (overlapping) flags

I'm picturing something like:
`updater signatures [resource, ...]` - outputs the signatures, line by line
`updater verify [resource, ...]` - exits with 0 if all the resource signatures are valid, 1 if not
`updater [actor] [resource, ...] [-t timestamp] [--dry-run]` - updates in place all resources with `actor`, falling back to `user.name`; if `dry-run` is specified, just echoes the update manifest to stdout 

The use of `--no-replace` as it currently is feels a bit awkward; but I'm not the one actually using the tool, so I'd appreciate your feedback

**Comment by bradder555** [comment]
> I wonder if the CLI might end up cleaner if it was just subcommands, instead of changing the output format with (overlapping) flags
> 
> I'm picturing something like: `updater signatures [resource, ...]` - outputs the signatures, line by line `updater verify [resource, ...]` - exits with 0 if all the resource signatures are valid, 1 if not `updater [actor] [resource, ...] [-t timestamp] [--dry-run]` - updates in place all resources with `actor`, falling back to `user.name`; if `dry-run` is specified, just echoes the update manifest to stdout
> 
> The use of `--no-replace` as it currently is feels a bit awkward; but I'm not the one actually using the tool, so I'd appreciate your feedback

I agree, I was kind of trying to maintain backwards compatibility, but I don't think anyone will mind if there are breaking changes. Maybe this can be a major revision :)

**Comment by paul-griffith** [comment]
Let me know how you'd like to proceed - obviously this PR has somewhat ballooned from your original intention, but I'd love to have a second pair of eyes on this repo going forward. I can merge this PR with or without your explicit review (all tests pass), manually push out a new release, and let you do what you will with it - you certainly have no obligation to donate any more of your time :)

**Comment by bradder555** [comment]
I'm happy to do a quick code review some time today :) will leave notes or
"LGTM"

Cheers

**Review by paul-griffith — APPROVED** [review]

**Pull request merged**
